title: Sebastian Coles
email: seb_coles@outlook.com
description: >- 
  DevSecOps Consultant | I bridge between CTO and CISO | Helping organisations ship great products securely, and at speed.
baseurl: ""
url: "https://sebcoles.github.io"
github_username:  sebcoles
google_analytics: G-TJCWV11W4Q
tiles-source: pages
tiles-count: 6
socials:
  GitHub: https://github.com/sebcoles
  LinkedIn: https://www.linkedin.com/in/sebastiancoles
markdown: kramdown
sass:
  style: compressed

