# site settings
title: Sebastian Coles
email: seb_coles@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  DevSecOps Consultant | I help organisations ship great products securely, and at speed.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sebcoles.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sebcoles
google_analytics: G-TJCWV11W4Q
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6
socials:
  GitHub: https://github.com/sebcoles
  LinkedIn: https://www.linkedin.com/in/sebastiancoles
markdown: kramdown
sass:
  style: compressed

